#!/bin/sh

/sbin/makedevs /dev < device.txt > /output.makedevs.txt 2>&1

. /bin/boot.functions

boot_default() {
	sh /bin/boot-hdd
}

mkdir /proc
mount -t proc proc /proc

# For debug purposes
mount -t usbfs usbfs /proc/bus/usb

# Show the version 
cat /buildrom-version > /dev/tty$VT

message "Trying to boot from hdd."
cd /bin
./boot-hdd
RET=$?
cd /

message "NOTICE: Starting the shell..."
openvt $VT /bin/ash
exec /bin/ash
