# Targets specifically for the kernel payload

$(OUTPUT_DIR)/kernel-payload.elf: $(PAYLOAD-y)
	@ echo "Building the ELF payload..."
	@ rm -f $@
	@ $(STAGING_DIR)/sbin/mkelfImage --type bzImage-i386 \
	--command-line=$(COMMAND_LINE) $(OUTPUT_DIR)/bzImage $@
	@ chmod 0644 $@

$(OUTPUT_DIR)/kernel-payload.elf.lzma: $(OUTPUT_DIR)/kernel-payload.elf
	@ echo "Compressing the ELF payload with lzma..."
	@ $(STAGING_DIR)/bin/lzma e $< $@  2> /dev/null
	@ $(BIN_DIR)/checkrom.sh $@
